spring.application.name=regret-board

spring.datasource.url=jdbc:postgresql://localhost:5432/regrets
spring.datasource.username=regretadmin
spring.datasource.password=neveragain

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true